### ISSUE TITLE
Linux .deb not working. Again.

### ISSUE THREAD

**Issue by Dylan-86** [pocketnetteam/pocketnet.gui#394] opened 2022-03-30 17:02 UTC
I just installed the last release, 0.7.17 - .deb on Ubuntu 21.10

Just like in 0.58: IT DOES NOT WORK AT ALL

The page is blank.

See attachment.
![image](https://user-images.githubusercontent.com/58813956/160891252-bd4dde24-70ac-48cb-9bce-d3384dbaa1bf.png)

**Comment by shpingalet007** [comment] 2022-05-04 09:23
_Duplicate of https://github.com/pocketnetteam/pocketnet.gui/issues/369_

**Comment by shpingalet007** [comment] 2022-07-18 11:17
As I know, it is fixed now. Closing this at this moment

**Closed by shpingalet007** 2022-07-18 11:17 UTC
Labels: 🐛 bug, duplicate, platform: linux
