### ISSUE TITLE
Vague error messages like "There are problems with node" need to be improved.

### ISSUE THREAD

**Issue by bulrush15** [pocketnetteam/pocketnet.gui#12] opened 2019-09-27 12:56 UTC
* Windows 10 with Pocketnet app v0.0.43

When I try to post a new post, or even edit a post, I sometimes get an error message "There are 
problems with node." The error messages should be much more specific. From that point on I cannot edit nor make a new post so I have to restart the app. A restart is the only thing that fixes this error. 

Better error messages will also help tech support too.

**Comment by andyoknen** [comment] 2021-03-02 11:20
The issue is fixed in newer versions.

**Closed by andyoknen** 2021-03-02 11:20 UTC
