### ISSUE TITLE
Crash under normal windows user: Javascript error - operation not permitted mkdir 'logs'

### ISSUE THREAD

**Issue by expressrussian** [pocketnetteam/pocketnet.gui#255] opened 2021-11-05 09:19 UTC
Hello,
Windows 10 20H2 19042.1288. I have installed windows client v0.4.72 for all users. 
I start the client as normal (non-admin) user.
A javascript error occurred in the main process
Uncaught exception: Error: EPERM: operation not permitted, mkdir 'logs'
at mkdirSync (fs.js:925:3).
I cannot copy/paste the text, the popup does not allow it.
I will try to attach the picture.
![20211105](https://user-images.githubusercontent.com/45077477/140487152-361593ab-f0e6-4af2-b35b-823d55ce2a13.jpg)
The program does not start after clicking OK on the popup.

**Comment by the-real-vortex-v** [comment] 2021-11-20 07:07
My understanding is that the program files directory is not writeable by normal users. The program needs to be run as administrator. I suggest you install the program in another directory that program files and see how it goes. Many programs complain about this because it was changed from windows 7.

**Comment by shpingalet007** [comment] 2022-11-05 10:41
I suppose that the issue is old and resolved. No information. Reopen if it is not. Closing for now

**Closed by shpingalet007** 2022-11-05 10:41 UTC
Labels: contribution type: 🐛 fix
