### ISSUE TITLE
Linux app not working. Again

### ISSUE THREAD

**Issue by Dylan-86** [pocketnetteam/pocketnet.gui#425] opened 2022-04-20 16:48 UTC
![image](https://user-images.githubusercontent.com/58813956/164282111-7deddde5-346d-4f72-9703-5463cdb3b6d8.png)

**Comment by shpingalet007** [comment] 2022-05-04 09:15
@Dylan-86, thanks for your activity on Bastyon 👍 We really appreciate your support. Our team will look into this soon. Don't hesitate to send more details if there are any.

_Duplicate of https://github.com/pocketnetteam/pocketnet.gui/issues/425_

**Comment by shpingalet007** [comment] 2022-07-18 11:15
As I know, it is fixed now. Closing this at this moment

**Closed by shpingalet007** 2022-07-18 11:15 UTC
Labels: 🐛 bug, duplicate, platform: linux
